### ISSUE TITLE
Simplify implementation of new SDKs

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/service-protocol#30]
This is an exploration issue for collecting and evaluating ideas for the service protocol that could simplify the implementation of new SDKs. The goal should be that implementing a new SDK should be possible within 2-3 weeks. Key to it are an easy to understand description of the protocol, clear concepts, optionality of more advanced features and ease of use.

```[tasklist]
### Tasks
- [ ] #28
- [ ] https://github.com/restatedev/service-protocol/issues/31
- [ ] https://github.com/restatedev/service-protocol/issues/32
- [ ] https://github.com/restatedev/service-protocol/issues/33
- [ ] https://github.com/restatedev/service-protocol/issues/34
- [ ] Have an invoker with a leaner/simplified protocol
- [ ] https://github.com/restatedev/service-protocol/issues/37
- [ ] https://github.com/restatedev/service-protocol/issues/39
```

**Comment by slinkydeveloper** [comment]
Nothing to do here for now
