### ISSUE TITLE
Allow end of stream without OutputStreamEntry

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/service-protocol#49]
Right now to end a stream:

> A message stream MUST start with StartMessage and MUST end with either:

>    One OutputStreamEntry
>    One [SuspensionMessage](https://github.com/restatedev/service-protocol/blob/main/service-invocation-protocol.md#suspension)
>    One [ErrorMessage](https://github.com/restatedev/service-protocol/blob/main/service-invocation-protocol.md#failures).
>    None of the above, which is equivalent to sending an empty [ErrorMessage](https://github.com/restatedev/service-protocol/blob/main/service-invocation-protocol.md#failures).

This assumes that a correct invocation always ends with a response, which is not the case for https://github.com/restatedev/restate/issues/899. We should modify the end of stream operations to not assume OutputStreamEntry is the last message. 

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/pull/1012
- [ ] https://github.com/restatedev/sdk-java/pull/193
- [ ] https://github.com/restatedev/sdk-typescript
```
